name: PullRequest
on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'
    tags:
      - 'v*.*.*'

jobs:
  context: 
    name: context
    runs-on: ubuntu-latest
    outputs:
      event-type: ${{ steps.config.outputs.event_type }}
      action: ${{ steps.config.outputs.action }}
    defaults:
      run:
        shell: bash
    steps:
      - name: github-context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: determine-action
        id: config
        run: |
          EVENT_NAME="${{ github.event_name }}"
          BRANCH="${GITHUB_REF#refs/heads/}"
          TAG="${GITHUB_REF#refs/tags/}"

          action=plan

          if [[ "$EVENT_NAME" == "push" && "$BRANCH" == "main" ]]; then
            event_type="merge"
            action="apply"
          fi

          if [[ ("$EVENT_NAME" == "push" || "$EVENT_NAME" == "release") && "$TAG" != "" ]]; then
            event_type="release"
            action="apply"
          fi

          echo event_name=$EVENT_NAME
          echo branch_name=$BRANCH
          echo tag=$TAG
          echo event_type=$event_type
          echo action=$action

          echo "event_type=$event_type" >> $GITHUB_OUTPUT
          echo "action=$action" >> $GITHUB_OUTPUT
        shell: bash

  list-changed-files:
    needs: [context]
    name: IdentifyChanges
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: print-outputs
        run: 
          echo "${{ needs.context.outputs.action }}"
          echo "${{ needs.context.outputs.event_type }}"
        shell: bash
  run-on-pr-event:
    if: github.event_name == 'pull_request'
    name: run-on-events
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: echo-event
        run: echo "Running on PR"
  run-on-push-to-main:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    name: run-on-push-to-main
    runs-on: ubuntu-latest
    steps:
      - name: on-push-to-main
        run: echo "Pushed to main"
  run-on-tag:
    name: on-tag-creation
    if: contains(github.ref, 'refs/tags') && github.event_name == 'push'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: on tag creation
        run: echo "On Tag Creation"