name: OnReleaseEvent

on: 
  release:
    types: [published]

jobs:
  event-trigger: 
    runs-on: ubuntu-latest
    steps: 
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: testing-event
        run: echo "${{ github.event }}"
        shell: bash