name: CreateRelease
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v3.1.0
      - name: get-all-merged-pull-requests
        id: get-all-merged-pull-requests
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: create-release
        uses: release-drafter/release-drafter@v5.20.0
        with:
          publish: ${{ !contains(steps.get-all-merged-pull-requests.outputs.labels, 'no-releases') }}
          prerelease: true
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}