name: OnReleaseEvent

on: 
  release:
    types: [published]

jobs:
  event-trigger: 
    runs-on: ubuntu-latest
    steps: 
      - name: testing-event
        run: echo "${{ github.event }}"
        shell: bash