name: TestRelease
on:
  release:
    types: [published]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps: 
      - name: print-github-context
        run: echo '${{ toJSON(github) }}'
        shell: bash