name: TestRelease
on:
  push:
    tags:
      - v0.**

jobs:
  testing:
    runs-on: ubuntu-latest
    steps: 
      - name: print-github-context
        run: echo '${{ toJSON(github) }}'
        shell: bash
